spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Specify your MySQL dialect here
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080  # Set your desired server port